Feature/code cleanup
gsundeep-tech/split-expense-ui pull request #3
Opened 2021-05-08 11:26 UTC by vigneshgowrabathuni

- Code cleanup changes

2021-05-08 11:30 UTC, gsundeep-tech commented
@vigneshgowrabathuni main.css file is not required. I have tested it without the main.css and it works. when the react application is starting at runtime main.css file is being generated.

2021-05-08 11:33 UTC, gsundeep-tech requested changes

2021-05-08 11:33 UTC, gsundeep-tech commented on package.json
> +    "build:css": "postcss src/styles/tailwind.css -o src/styles/main.css"
Somehow "build:css" was not working for me. so I have used cssx. Have you tested it?

2021-05-08 11:33 UTC, gsundeep-tech commented on public/index.html
> +<head>
Thanks for cleaning the html

2021-05-08 11:33 UTC, gsundeep-tech commented on package.json
> -    "@craco/craco": "^6.1.1",
Thanks for removing the library. Is it working without this library?

2021-05-08 11:33 UTC, gsundeep-tech commented on src/App.css
> -
Thanks for cleaning the css

2021-05-08 16:31 UTC, vigneshgowrabathuni commented on package.json
> +    "build:css": "postcss src/styles/tailwind.css -o src/styles/main.css"
@gsundeep-tech Yes it's working fine in local. `cssx `is not a good name so i have changes it to `build:css`

2021-05-08 16:35 UTC, gsundeep-tech commented
> @vigneshgowrabathuni main.css file is not required. I have tested it without the main.css and it works. when the react application is starting at runtime main.css file is being generated.

@vigneshgowrabathuni  please remove the main.css file

2021-05-09 05:09 UTC, vigneshgowrabathuni commented on package.json
> -    "@craco/craco": "^6.1.1",
Yes It's working.

2021-05-09 05:10 UTC, vigneshgowrabathuni commented
@gsundeep-tech I have removed the `main.css` file and add it in the` .gitignore` to skip in the future while pushing the code.

2021-05-09 07:42 UTC, gsundeep-tech approved these changes

2021-05-09 07:42 UTC, merged